Change mpifx_comm to mpi_f08
dftbplus/mpifx pull request #55
Opened 2024-01-27 11:15 UTC by jubich

2024-02-06 15:35 UTC, aradi requested changes

2024-02-06 15:35 UTC, aradi commented on lib/mpifx_comm.fpp
> +    type(mpi_comm) :: newcomm_
Let's use `newmpicomm` instead of the `newcomm_` with the trailing underscore.

2024-04-01 10:55 UTC, bhourahine reviewed
I can't make a suggestion for line 42 (due to github's limitation to only close to changed lines):
\param commid  MPI Communicator (default: \c MPI_COMM_WORLD)

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +  subroutine mpifx_comm_init_int(self, commid, error)
Can you please add comments for the routine, but also why is is called _init_int() ? This is not very informative.
```suggestion
  !> Initializes a communicator from a numerical id.
  !!
  !! \param self  Initialized instance on exit.
  !! \param commid  Numerical MPI Communicator ID
  !! \param error  Error flag on return containing the first error occurring
  !!     during the calls mpi_comm_size and mpi_comm_rank.
  !!
  subroutine mpifx_comm_from_id(self, commid, error)
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +  end subroutine mpifx_comm_init_int
```suggestion
  end subroutine mpifx_comm_from_id
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +    procedure, private :: mpifx_comm_init_int
```suggestion
    procedure, private :: mpifx_comm_from_id
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +    procedure, private :: mpifx_comm_init_comm
```suggestion
    procedure, private :: mpifx_comm_from_type
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +    generic :: init => mpifx_comm_init_int, mpifx_comm_init_comm
```suggestion
    generic :: init => mpifx_comm_from_id, mpifx_comm_from_type
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +  subroutine mpifx_comm_init_comm(self, comm, error)
```suggestion
  subroutine mpifx_comm_from_type(self, comm, error)
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
> +  end subroutine mpifx_comm_init_comm
```suggestion
  end subroutine mpifx_comm_from_type
```

2024-04-01 10:55 UTC, bhourahine commented on lib/mpifx_comm.fpp
>    !! \param error  Error flag on return containing the first error occuring
```suggestion
  !! \param error  Error flag on return containing the first error occurring
```

2024-04-08 14:04 UTC, bhourahine approved these changes
Ready to merge

2024-04-08 14:04 UTC, merged